Var can be any type and type is defined based on the value. Data types are - int, float, str, bool, tuple and set and dictionary

List is ordered, mututable, collection
a = [1, 2, 3, 4]

List can have different data types ( which is different than Java, Javascript. Heterogenous
They can expand or shrink as needed, and can have duplicates

apend()
remove()
[1] = 1

Tuple

Ordered
Inmututable
a = (1, 3, 4)

Set
unordered
collection of unique values
a = {1, 2, 3}
add()
remove()

Dictionary
Key and value pairs

k = {"name":"Rohit", "email":"itt"}

Operators
and
not
in
is
x>y and x<z -

Slicing is a techqinue in Python to extract a subset from a collection
seq[Start:Stop:Step]

Start - inclusive
Stop - exclusive, up to highest
Step - Default 1

Negative indexes is used for from end. Last element is -1

In [ ]:
type(1==2)

bool

If and for doesn't use curly braces. They use indendation to show the scope
if x<5
elif -
else

for variable in sequence
while condition

def functionname (arguments)
return

call by using functionname()

In [ ]:
import numpy as np
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
np.zeros(shape=(4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr = np.arange(10)

In [ ]:
(arr>2) & (arr<5)

array([False, False, False,  True,  True, False, False, False, False,
       False])

In [ ]:
arr[(arr>2) & (arr<5)].mean()

np.float64(3.5)

In [ ]:
import pandas as pd
df = pd.read_csv("http://raw.githubusercontent.com/agconti/kaggle-titanic/master/data/train.csv")

In [ ]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [ ]:
df[['Age', 'Fare']]

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [ ]:
#filtering
df['Fare'] > 15

0      False
1       True
2      False
3       True
4      False
       ...
886    False
887     True
888     True
889     True
890    False
Name: Fare, Length: 891, dtype: bool

In [ ]:
df[df['Fare'] > 15]['Fare'].mean()

np.float64(56.90295357967668)

In [ ]:
df.sort_values('Age', ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [ ]:
df['Age'].isna().sum()

np.int64(177)

In [ ]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [ ]:
df['Age'].isna().sum()

np.int64(0)

In [ ]:
agreegated_values = df.groupby('Survived').agg(
    {'Age':['mean', 'median'],
     'Fare':'mean'}
)

In [ ]:
agreegated_values.iloc[0,0]

np.float64(30.415099646415943)

In [ ]:
agreegated_values

                Age                  Fare
               mean     median       mean
Survived
0         30.415100  29.699118  22.117887
1         28.549778  29.699118  48.395408

In [ ]:
agreegated_values.loc[0,'Fare']

mean    22.117887
Name: 0, dtype: float64